### ISSUE TITLE
Cloning Error

### ISSUE THREAD

**Issue by hedii-mejri** [pratikju/go-chat#1]
When trying to clone project using the go get command, I get the following error : 

"\src\github.com\pratikju\go-chat\session\session.go:12: cannot use "{\"cookieName\":\"gosessionid\",\"gclifetime\":3600}" (type string) as type *session.ManagerConfig in argument to session.NewManager  "

**Comment by pratikju** [comment]
NewManager signature has been changed as per latest package. Cloning should work fine now :)

**Comment by hedii-mejri** [comment]
Thanks!
It works now :)

_MEJRI Hédi - NIDS (__Network, Infrastructure and Data Security)_

_Leo - Tunis Doyen_

**Comment by pratikju** [comment]
Closing the issue then.
